[package]
name = "aire-filters"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os="android")'.dependencies]
jni = "0.21.1"
ndk-sys = { version = "0.6.0", features = ["bitmap"] }
ndk = "0.9.0"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
colorutils-rs = "0.3.1"
half = "2.4.1"
histogram_equalization = "0.1.0"
libblur = "0.10.3"
num-traits = "0.2.19"
pic-scale = "0.1.0"
yuvutils-rs = "0.2.1"




