[package]
name = "aire-filters"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os="android")'.dependencies]
jni = "0.21.1"
ndk-sys = { version = "0.6.0", features = ["bitmap"] }
ndk = "0.9.0"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
colorutils-rs = "0.4.10"
half = { version = "2.4.1", default-features = true, features = ["std", "alloc", "num-traits"] }
histogram_equalization = "0.1.0"
libblur = "0.13.0"
num-traits = "0.2.19"
pic-scale = "0.1.20"
yuvutils-rs = "0.3.0"
